### ISSUE TITLE
Your examples contain some bugs

### ISSUE THREAD

**Issue by frog89** [react-bootstrap/code-sandbox-examples#82]
**Tested with following config:** 
Win 10 + Chrome and also Win10 + Firefox

**Error 1:** When running your Sass Example in code sandbox, I get following error when clicking on the "here" link:
SecurityError
Failed to execute 'replaceState' on 'History': A history state object with URL 'https://getbootstrap.com/docs/4.3/getting-started/theming/#importing' cannot be created in a document with origin 'https://ob4fg.csb.app' and URL 'https://ob4fg.csb.app/'.

**Error 2:** When running your Parcel Example (same in Parcel Typescript example) in code sandbox, I get the error below:
Error
Target container is not a DOM element.
▶ 1 stack frames were collapsed.
evaluate
/src/index.js:43:9

  40 | );
  41 | 
  42 | var mountNode = document.getElementById('root');
> 43 | ReactDOM.render(<App />, mountNode);
     |         ^
  44 | 

View compiled

**Comment by mxschmitt** [comment]
Regarding error 1, a bug report was opened on the CodeSandbox client. Pretty sure, that this is not related to our code: https://github.com/codesandbox/codesandbox-client/issues/4100

Regarding error 2, thats probably also not something related to us. Because if you rerender / change something it will work. Seems like the DOM order is not persistent, due the root element is not there if the script will be loaded. Maybe that: https://github.com/codesandbox/codesandbox-client/issues/2087
